### ISSUE TITLE
Upcoming EDMC 5.0.0 changes

### ISSUE THREAD

**Issue by Athanasius** [seldonlabs/edmc_clog#1]
We're moving all the static data into an edmc_data.py file.

I see you're making use of the 'dashboard' flags currently defined in plug.py, so you'll need to cater for them being in edmc_data.py instead (do the try/except thing with initial attempt to import edmc_data, and then as you're only using the one I guess just `from edmc_data import FlagsSupercruise` will do ?).

**Comment by seldonlabs** [comment]
Thanks for the heads-up! Yes, the import exception should be the cleaner way.

**Comment by seldonlabs** [comment]
addressed by: https://github.com/seldonlabs/edmc_clog/commit/b7637ebfe8c1589c30e83103d5931899541a3af5

**Comment by Athanasius** [comment]
Btw, the extra Flasg2 values in launch Odyssey have been added in to `develop`... I hope to get 5.0.2 out based on that tomorrow latest.
